// packages/f-react/src/Login.jsx
import React, { Component } from 'react'
import { AUTH_TOKEN } from './constants'

import { Mutation } from 'react-apollo'
import gql from 'graphql-tag'

const LOGIN_MUTATION = gql`
  mutation LoginMutation($email: String!, $pwd: String!) {
    signin(signinInput: { email: $email, pwd: $pwd }) {
      expiresIn
      accessToken
    }
  }
`

class Login extends Component {
  state = {
    email: '',
    pwd: '',
    name: ''
  }
  render() {
    const { email, pwd } = this.state
    return (
      <div className="login">
        <div className="form-line">
          <input
            value={email}
            onChange={(e) => this.setState({ email: e.target.value })}
            type="text"
            placeholder="Your email address"
          />{' '}
          <input
            value={pwd}
            onChange={(e) => this.setState({ pwd: e.target.value })}
            type="password"
            placeholder="Choose a safe password"
          />
        </div>
        <Mutation
          mutation={LOGIN_MUTATION}
          variables={{ email, pwd }}
          onCompleted={(data) => this._confirm(data)}
        >
          {(mutation) => (
            <div className=" button" onClick={mutation}>
              {'login'}
            </div>
          )}
        </Mutation>
      </div>
    )
  }

  _confirm = async (data) => {
    const { accessToken } = data.signin
    this._saveUserData(accessToken)
  }
  _saveUserData = (token) => {
    localStorage.setItem(AUTH_TOKEN, token)
  }
}

export default Login

// src/views/Login.vue
<template>
  <div class="login">
    <ApolloMutation
      :mutation="require('../graphql/signin.gql')"
      :variables="{
        signinInput: {
          email: email,
          pwd: pwd
        },
      }"
      class="form"
      @done="handleLogin"
      @error="handleLoginFail"
    >
      <template slot-scope="{ mutate }">
        <form v-on:submit.prevent="formValid && mutate()">
          <label for="field-email">Email</label>
          <input id="field-email" v-model="email" placeholder="Type Email" class="input">
          <label for="field-password">Password</label>
          <input
            id="field-password"
            v-model="pwd"
            placeholder="Type Password"
            class="input"
            type="password"
          >
          <input type="submit" value="Login">
        </form>
      </template>
    </ApolloMutation>
    <hr>
    <div class="flex">
      <div class="a">0</div>
      <div class="b">{{ progress }} %</div>
      <div class="c">{{ expiresIn }}</div>
    </div>
  </div>
</template>

<script>
import { AUTH_TOKEN } from "../constant";

export default {
  data() {
    return {
      email: "",
      pwd: "",
      preset: {
        expiresIn: localStorage.getItem(`${AUTH_TOKEN}_exp`) || 3600,
        stamp: localStorage.getItem(`${AUTH_TOKEN}_stamp`) || 0
      },
      snapStamp: +new Date()
    };
  },
  computed: {
    formValid() {
      return this.email && this.pwd;
    },
    expiresIn: {
      get() {
        return this.preset.expiresIn;
      },
      set(val) {
        localStorage.setItem(`${AUTH_TOKEN}_exp`, val);
        this.preset.expiresIn = val;
      }
    },
    stamp: {
      get() {
        return this.preset.stamp;
      },
      set(val) {
        localStorage.setItem(`${AUTH_TOKEN}_stamp`, val);
        this.preset.stamp = val;
        this.snapStamp = val;
      }
    },
    progress() {
      return (
        Math.round(
          Math.min(this.snapStamp - this.stamp, this.expiresIn * 1000) /
            this.expiresIn
        ) / 10
      );
    }
  },
  methods: {
    handleLogin(loginObj) {
      const {
        data: {
          signin: { expiresIn, accessToken }
        }
      } = loginObj;
      localStorage.setItem(AUTH_TOKEN, accessToken);
      this.expiresIn = expiresIn;
      this.stamp = +new Date();
    },
    handleLoginFail(errObj) {
      this.$message.error(errObj.gqlError.message.error);
    }
  }
};
</script>

<style lang="less" scoped>
.login {
  text-align: center;
  .flex {
    width: 320px;
    > div {
      flex: 1;
    }
  }
}
</style>
